name: Publish on GitHub, Modrinth

on: [ push, workflow_dispatch ]

env:
  MINECRAFT_VERSION: 1.21.1
  RELEASE_NAME: Automatic Script Upload
  MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.RR_GIT_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build
        run: ./gradlew build
      - name: Publish (Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: 2RF6gKzx
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          github-token: "${{env.GITHUB_TOKEN}}"

          name: "${{env.RELEASE_NAME}}"
          version-type: alpha

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "21"
